// <auto-generated />
using FacialRecognitionTimekeepingAPI.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FacialRecognitionTimekeepingAPI.Migrations
{
    [DbContext(typeof(TimekeepingContext))]
    [Migration("20200908124630_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FacialRecognitionTimekeepingAPI.Models.TimekeepingPerson", b =>
                {
                    b.Property<string>("AliasId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CognitivePersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AliasId");

                    b.ToTable("TimekeepingPeople");
                });

            modelBuilder.Entity("FacialRecognitionTimekeepingAPI.Models.TimekeepingRecord", b =>
                {
                    b.Property<string>("AliasId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TimekeepingRecordUnixTimestampSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("AliasId", "TimekeepingRecordUnixTimestampSeconds");

                    b.ToTable("TimekeepingRecords");
                });

            modelBuilder.Entity("FacialRecognitionTimekeepingAPI.Models.TimekeepingRecord", b =>
                {
                    b.HasOne("FacialRecognitionTimekeepingAPI.Models.TimekeepingPerson", "TimekeepingPerson")
                        .WithMany("TimekeepingRecords")
                        .HasForeignKey("AliasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
